### ISSUE TITLE
Doesn't work with a base_url of "/"

### ISSUE THREAD

**Issue by jackmcdade** [statamic/ssg#1]
Is there a reason we can't support a scheme/host-less URL pattern? I have it kinda working locally but am running in an odd URL generation bug where the base is `/:/`.

The primary issue lies in `Request.php` – it'll throw undefined index errors because there won't be a scheme or host.

**Comment by jasonvarga** [comment]
When a page is generated, we're basically just faking a request. The request needs to know where it's being served from. It builds itself through server variables. 

I fake it using the URL in the config since in the CLI you are nowhere. The CLI doesn't know where it is. Where it might end up. Who it is. What it is. If it is.

**Comment by jackmcdade** [comment]
[What it is](https://getyarn.io/yarn-clip/394e938d-a24f-4a6e-beee-8248b6ba87db)
